// Auto-generated by scripts/buildCatalogs.ts.
// Do not edit directly; update seeds or extraction scripts.

import type { AgentDefinition } from '@/lib/catalogTypes';

export const generatedAgentCatalog: AgentDefinition[] = [
  {
    "key": "payment_status_inquiry",
    "name": "Payment Status Inquiry",
    "description": "Description inferred from deck text; manual review recommended.",
    "defaultInstructions": "Resolve payment status inquiries by matching supplier, invoice, payment, and remittance records and drafting a supplier-ready summary.",
    "dependsOnDomains": [
      "supplier_master",
      "supplier_contacts",
      "invoice_header",
      "payments",
      "payment_linking"
    ],
    "dependsOnFields": [
      "supplier_id",
      "contact_email",
      "invoice_number",
      "invoice_id",
      "payment_id"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "(payment inquiry, invoice,"
    }
  },
  {
    "key": "duplicate_invoice_detection",
    "name": "Duplicate Invoice Detection",
    "description": "AppZen Inbox is an AI-driven",
    "defaultInstructions": "Compare incoming invoices against historical headers/lines and flag likely duplicates with confidence and rationale.",
    "dependsOnDomains": [
      "supplier_master",
      "invoice_header",
      "invoice_lines"
    ],
    "dependsOnFields": [
      "supplier_id",
      "invoice_number",
      "invoice_id",
      "invoice_amount",
      "invoice_date"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": false
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "relationships, and duplicate invoices."
    }
  },
  {
    "key": "tax_form_w9_compliance",
    "name": "Tax Form (W-9) Compliance",
    "description": "to payment inquiries and statements. But this",
    "defaultInstructions": "Monitor tax-document status per supplier and generate follow-up tasks for missing or expiring forms.",
    "dependsOnDomains": [
      "supplier_master",
      "supplier_contacts",
      "tax_documents"
    ],
    "dependsOnFields": [
      "supplier_id",
      "contact_email",
      "tax_form_type",
      "tax_form_status"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "AP communication, from invoices and tax forms"
    }
  },
  {
    "key": "vendor_statement_reconciliation",
    "name": "Vendor Statement Reconciliation",
    "description": "Reconciling vendor statements means manually verifying payment status for",
    "defaultInstructions": "Reconcile vendor statement items against invoices, credits, and linked payments; produce exception list and proposed actions.",
    "dependsOnDomains": [
      "supplier_master",
      "invoice_header",
      "payments",
      "payment_linking",
      "credits",
      "purchase_orders"
    ],
    "dependsOnFields": [
      "supplier_id",
      "invoice_id",
      "payment_id",
      "credit_id",
      "po_number"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "Vendor Statement Reconciliation"
    }
  },
  {
    "key": "bank_account_change_request",
    "name": "Bank Account Change Request",
    "description": "Vendor communications requesting payment redirects create wire fraud risk",
    "defaultInstructions": "Validate sender identity, compare existing banking details, and route high-risk bank-change requests for confirmation.",
    "dependsOnDomains": [
      "supplier_master",
      "supplier_contacts",
      "supplier_banking"
    ],
    "dependsOnFields": [
      "supplier_id",
      "contact_email",
      "bank_account_last4"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "Bank Account Change Request"
    }
  },
  {
    "key": "no_po_no_pay_policy",
    "name": "No PO No Pay Policy",
    "description": "Invoices arriving without matching purchase orders create approval",
    "defaultInstructions": "Evaluate invoices against PO and goods receipt policy; explain whether the invoice is compliant or blocked.",
    "dependsOnDomains": [
      "invoice_header",
      "invoice_lines",
      "purchase_orders",
      "goods_receipts"
    ],
    "dependsOnFields": [
      "invoice_id",
      "po_number",
      "receipt_status"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "No PO No Pay Policy"
    }
  },
  {
    "key": "invoice_hold_reason_explainer",
    "name": "Invoice Hold Reason Explainer",
    "description": "Vendors asking “Why is my invoice on hold?” create high-volume follow-up",
    "defaultInstructions": "Use invoice exception records to explain hold causes and recommend next steps for AP and suppliers.",
    "dependsOnDomains": [
      "invoice_header",
      "invoice_exceptions",
      "invoice_lines"
    ],
    "dependsOnFields": [
      "invoice_id",
      "hold_reason_code",
      "hold_reason_text"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "Invoice Hold Reason Explainer"
    }
  },
  {
    "key": "remittance_proof_of_payment",
    "name": "Remittance & Proof-of-Payment Assistant",
    "description": "Vendors requesting payment confirmations and remittance advice consume",
    "defaultInstructions": "Retrieve remittance references and payment-to-invoice links and draft proof-of-payment responses.",
    "dependsOnDomains": [
      "invoice_header",
      "payments",
      "payment_linking"
    ],
    "dependsOnFields": [
      "invoice_id",
      "payment_id",
      "remittance_reference"
    ],
    "emailCapabilities": {
      "needsRead": true,
      "needsSend": true
    },
    "sourceRef": {
      "pdf": "deck",
      "note": "Remiance & Proof-of-Payment Assistant"
    }
  }
];
