// Auto-generated by scripts/buildCatalogs.ts.
// Do not edit directly; update seeds or extraction scripts.

import type { SchemaDomain } from '@/lib/catalogTypes';

export const generatedSchemaCatalog: SchemaDomain[] = [
  {
    "domainKey": "supplier_master",
    "label": "Supplier Master",
    "fields": [
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "payment_status_inquiry",
          "duplicate_invoice_detection",
          "vendor_statement_reconciliation",
          "bank_account_change_request",
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "blocked": [
            "Agent cannot match supplier records across invoices, payments, and communication history."
          ]
        },
        "description": "Field used in Supplier Master.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "supplier_name",
        "label": "Supplier Name",
        "requirement": "mandatory",
        "usedByAgents": [
          "payment_status_inquiry",
          "duplicate_invoice_detection",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "blocked": [
            "Supplier-facing responses may resolve to the wrong legal entity."
          ]
        },
        "description": "Field used in Supplier Master.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "supplier_status",
        "label": "Supplier Status",
        "requirement": "recommended",
        "usedByAgents": [
          "bank_account_change_request",
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "degraded": [
            "Compliance prioritization degrades without active/inactive supplier state."
          ]
        },
        "description": "Field used in Supplier Master.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "supplier_contacts",
    "label": "Supplier Contacts",
    "fields": [
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "payment_status_inquiry",
          "bank_account_change_request"
        ],
        "impactIfMissing": {
          "blocked": [
            "Contact routing and identity verification cannot be completed."
          ]
        },
        "description": "Field used in Supplier Contacts.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "contact_email",
        "label": "Contact Email",
        "requirement": "mandatory",
        "usedByAgents": [
          "payment_status_inquiry",
          "bank_account_change_request",
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "blocked": [
            "Agent cannot validate sender or respond to trusted supplier contact."
          ]
        },
        "description": "Field used in Supplier Contacts.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "contact_role",
        "label": "Contact Role",
        "requirement": "recommended",
        "usedByAgents": [
          "bank_account_change_request"
        ],
        "impactIfMissing": {
          "degraded": [
            "Fraud control confidence degrades when requestor role is unavailable."
          ]
        },
        "description": "Field used in Supplier Contacts.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "supplier_banking",
    "label": "Supplier Banking",
    "fields": [
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "bank_account_change_request",
          "payment_status_inquiry"
        ],
        "impactIfMissing": {
          "blocked": [
            "Bank account controls cannot map records to the requesting supplier."
          ]
        },
        "description": "Field used in Supplier Banking.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "bank_account_last4",
        "label": "Bank Account Last4",
        "requirement": "mandatory",
        "usedByAgents": [
          "bank_account_change_request"
        ],
        "impactIfMissing": {
          "blocked": [
            "Bank-change verification is blocked without baseline account identity."
          ]
        },
        "description": "Field used in Supplier Banking.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "bank_country",
        "label": "Bank Country",
        "requirement": "optional",
        "usedByAgents": [
          "bank_account_change_request"
        ],
        "impactIfMissing": {
          "restricted": [
            "Cross-border risk screening is limited without bank geography context."
          ]
        },
        "description": "Field used in Supplier Banking.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "invoice_header",
    "label": "Invoice Header",
    "fields": [
      {
        "key": "invoice_id",
        "label": "Invoice ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "invoice_hold_reason_explainer",
          "no_po_no_pay_policy",
          "vendor_statement_reconciliation",
          "payment_status_inquiry",
          "remittance_proof_of_payment"
        ],
        "impactIfMissing": {
          "blocked": [
            "Invoice-level joins are blocked for status, remittance, and hold use cases."
          ]
        },
        "description": "Field used in Invoice Header.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "payment_status_inquiry",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "blocked": [
            "Cross-domain matching to supplier and payment records fails."
          ]
        },
        "description": "Field used in Invoice Header.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "invoice_number",
        "label": "Invoice Number",
        "requirement": "mandatory",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "payment_status_inquiry"
        ],
        "impactIfMissing": {
          "blocked": [
            "Duplicate detection and supplier status response are blocked."
          ]
        },
        "description": "Field used in Invoice Header.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "invoice_amount",
        "label": "Invoice Amount",
        "requirement": "recommended",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "degraded": [
            "Matching precision degrades for duplicate and statement reconciliation checks."
          ]
        },
        "description": "Field used in Invoice Header.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "invoice_date",
        "label": "Invoice Date",
        "requirement": "recommended",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "payment_status_inquiry"
        ],
        "impactIfMissing": {
          "degraded": [
            "Time-window matching and aging analysis degrades."
          ]
        },
        "description": "Field used in Invoice Header.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "po_number",
        "label": "PO Number",
        "requirement": "recommended",
        "usedByAgents": [
          "no_po_no_pay_policy",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "degraded": [
            "PO-policy checks degrade without direct invoice-to-PO linking."
          ]
        },
        "description": "Field used in Invoice Header.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "invoice_lines",
    "label": "Invoice Lines",
    "fields": [
      {
        "key": "invoice_id",
        "label": "Invoice ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "no_po_no_pay_policy"
        ],
        "impactIfMissing": {
          "blocked": [
            "Line-level validation cannot attach to invoice header."
          ]
        },
        "description": "Field used in Invoice Lines.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "line_amount",
        "label": "Line Amount",
        "requirement": "recommended",
        "usedByAgents": [
          "duplicate_invoice_detection",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "degraded": [
            "Variance checks and anomaly scoring degrade at line level."
          ]
        },
        "description": "Field used in Invoice Lines.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "line_description",
        "label": "Line Description",
        "requirement": "optional",
        "usedByAgents": [
          "invoice_hold_reason_explainer"
        ],
        "impactIfMissing": {
          "restricted": [
            "Hold explanation narratives are more generic without line context."
          ]
        },
        "description": "Field used in Invoice Lines.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "invoice_exceptions",
    "label": "Invoice Exceptions",
    "fields": [
      {
        "key": "invoice_id",
        "label": "Invoice ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "invoice_hold_reason_explainer"
        ],
        "impactIfMissing": {
          "blocked": [
            "Cannot retrieve exception details for hold analysis."
          ]
        },
        "description": "Field used in Invoice Exceptions.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "hold_reason_code",
        "label": "Hold Reason Code",
        "requirement": "mandatory",
        "usedByAgents": [
          "invoice_hold_reason_explainer"
        ],
        "impactIfMissing": {
          "blocked": [
            "Hold reason explainer is blocked without coded hold reason."
          ]
        },
        "description": "Field used in Invoice Exceptions.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "hold_reason_text",
        "label": "Hold Reason Text",
        "requirement": "recommended",
        "usedByAgents": [
          "invoice_hold_reason_explainer"
        ],
        "impactIfMissing": {
          "degraded": [
            "Human-readable hold explanation quality degrades."
          ]
        },
        "description": "Field used in Invoice Exceptions.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "purchase_orders",
    "label": "Purchase Orders",
    "fields": [
      {
        "key": "po_number",
        "label": "PO Number",
        "requirement": "mandatory",
        "usedByAgents": [
          "no_po_no_pay_policy",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "blocked": [
            "No PO No Pay policy checks are blocked without PO references."
          ]
        },
        "description": "Field used in Purchase Orders.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "po_status",
        "label": "PO Status",
        "requirement": "recommended",
        "usedByAgents": [
          "no_po_no_pay_policy"
        ],
        "impactIfMissing": {
          "degraded": [
            "Policy outcomes degrade for closed/open PO distinction."
          ]
        },
        "description": "Field used in Purchase Orders.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "recommended",
        "usedByAgents": [
          "no_po_no_pay_policy"
        ],
        "impactIfMissing": {
          "degraded": [
            "PO matching confidence declines when supplier linkage is absent."
          ]
        },
        "description": "Field used in Purchase Orders.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "goods_receipts",
    "label": "Goods Receipts",
    "fields": [
      {
        "key": "po_number",
        "label": "PO Number",
        "requirement": "mandatory",
        "usedByAgents": [
          "no_po_no_pay_policy"
        ],
        "impactIfMissing": {
          "blocked": [
            "Cannot verify receipt linkage for No PO No Pay."
          ]
        },
        "description": "Field used in Goods Receipts.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "receipt_status",
        "label": "Receipt Status",
        "requirement": "recommended",
        "usedByAgents": [
          "no_po_no_pay_policy"
        ],
        "impactIfMissing": {
          "degraded": [
            "Policy decisions degrade for partial/in-transit receipt states."
          ]
        },
        "description": "Field used in Goods Receipts.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "payments",
    "label": "Payments",
    "fields": [
      {
        "key": "payment_id",
        "label": "Payment ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "payment_status_inquiry",
          "remittance_proof_of_payment"
        ],
        "impactIfMissing": {
          "blocked": [
            "Payment tracking and proof retrieval are blocked."
          ]
        },
        "description": "Field used in Payments.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "invoice_id",
        "label": "Invoice ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "payment_status_inquiry",
          "vendor_statement_reconciliation",
          "remittance_proof_of_payment"
        ],
        "impactIfMissing": {
          "blocked": [
            "Cannot map payments to invoice references."
          ]
        },
        "description": "Field used in Payments.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "payment_date",
        "label": "Payment Date",
        "requirement": "recommended",
        "usedByAgents": [
          "payment_status_inquiry",
          "remittance_proof_of_payment"
        ],
        "impactIfMissing": {
          "degraded": [
            "Status responses lose timing details and SLA confidence."
          ]
        },
        "description": "Field used in Payments.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "payment_amount",
        "label": "Payment Amount",
        "requirement": "recommended",
        "usedByAgents": [
          "payment_status_inquiry",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "degraded": [
            "Amount-level reconciliation confidence degrades."
          ]
        },
        "description": "Field used in Payments.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "payment_linking",
    "label": "Payment Linking",
    "fields": [
      {
        "key": "payment_id",
        "label": "Payment ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "remittance_proof_of_payment",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "blocked": [
            "Remittance lineage from payment to invoice cannot be established."
          ]
        },
        "description": "Field used in Payment Linking.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "invoice_id",
        "label": "Invoice ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "remittance_proof_of_payment",
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "blocked": [
            "Proof-of-payment cannot attach to invoice records."
          ]
        },
        "description": "Field used in Payment Linking.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "remittance_reference",
        "label": "Remittance Reference",
        "requirement": "recommended",
        "usedByAgents": [
          "remittance_proof_of_payment"
        ],
        "impactIfMissing": {
          "degraded": [
            "Response quality degrades without remittance IDs for suppliers."
          ]
        },
        "description": "Field used in Payment Linking.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "credits",
    "label": "Credits",
    "fields": [
      {
        "key": "credit_id",
        "label": "Credit ID",
        "requirement": "optional",
        "usedByAgents": [
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "restricted": [
            "Credit memo offsets are limited in reconciliation outcomes."
          ]
        },
        "description": "Field used in Credits.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "optional",
        "usedByAgents": [
          "vendor_statement_reconciliation"
        ],
        "impactIfMissing": {
          "restricted": [
            "Credit matching confidence is limited without supplier linkage."
          ]
        },
        "description": "Field used in Credits.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  },
  {
    "domainKey": "tax_documents",
    "label": "Tax Documents",
    "fields": [
      {
        "key": "supplier_id",
        "label": "Supplier ID",
        "requirement": "mandatory",
        "usedByAgents": [
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "blocked": [
            "Tax-document compliance cannot map to supplier entity."
          ]
        },
        "description": "Field used in Tax Documents.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "tax_form_type",
        "label": "Tax Form Type",
        "requirement": "mandatory",
        "usedByAgents": [
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "blocked": [
            "Cannot determine whether W-9 equivalent document was submitted."
          ]
        },
        "description": "Field used in Tax Documents.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "tax_form_status",
        "label": "Tax Form Status",
        "requirement": "mandatory",
        "usedByAgents": [
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "blocked": [
            "Compliance status workflow is blocked without document status."
          ]
        },
        "description": "Field used in Tax Documents.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      },
      {
        "key": "expiration_date",
        "label": "Expiration Date",
        "requirement": "recommended",
        "usedByAgents": [
          "tax_form_w9_compliance"
        ],
        "impactIfMissing": {
          "degraded": [
            "Proactive renewal reminders and risk prioritization degrade."
          ]
        },
        "description": "Field used in Tax Documents.",
        "sourceRef": {
          "pdf": "schema",
          "note": "Parsed from schema PDF text with manual normalization."
        }
      }
    ]
  }
];
